name: Docker Image CI

on:
  push:
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        
    - name: Get the version
      id: get_version
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
    - name: Build and optionally push docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ihmeuwdemographics/base
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}

    - name: Identify package versions
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
      run: |
        chmod +x ./installed_versions/scripts/get_versions.sh
        ./installed_versions/scripts/get_versions.sh ${{ steps.get_version.outputs.VERSION }}

    - uses: stefanzweifel/git-auto-commit-action@v4
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
      with:
        commit_message: "Document software/package versions included in new tagged build"
        branch: master
